version: "3.8"
services:
  dev:
    image: klakegg/hugo:ext-alpine
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"

  publish:
    image: klakegg/hugo:ext-alpine
    command: --baseUrl https://s3.amazonaws.com/aws-workshop.redislabs.com
    volumes:
      - ".:/src"

  production:
    image: klakegg/hugo:ext-alpine
    entrypoint: [""]
    command: hugo deploy
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ".:/src"
      - "$HOME/.aws:/root/.aws"

